# Default values for suricata.
replicaCount: 1

image:
  repository: registry.hub.docker.com/jasonish/suricata
  pullPolicy: IfNotPresent
  tag: "7.0"

interface: eth0

# Host path for suricata log volume
suricata_log_path: /opt/suricata

# Specify the node label for determining where to run Suricata
node_label: "kubernetes.io/os"
node_label_value: "linux"

logrotate_settings: |
  /var/log/suricata/*.log /var/log/suricata/*.json {
    daily
    missingok
    rotate 10
    nocompress
    sharedscripts
    postrotate
        suricatasc -c reopen-log-files
    endscript
  }
