# Default values for suricata.
replicaCount: 1

image:
  repository: registry.hub.docker.com/jasonish/suricata
  pullPolicy: IfNotPresent
  tag: "7.0"

interface: eth0

# Host path for suricata log volume
suricata_log_path: /opt/suricata

# Specify the node label for determining where to run Suricata
node_label: "kubernetes.io/os"
node_label_value: "linux"