# Default values for suricata.
replicaCount: 1
namespace: suricata

image:
  repository: registry.hub.docker.com/jasonish/suricata
  pullPolicy: IfNotPresent
  tag: "7.0"

capture_interface: capture0

# Host path for suricata log volume
suricata_log_path: /opt/suricata
suricata_pcap_path: /opt/suricata/pcaps

logrotate_config:
  suricata: |
    /var/log/suricata/*.log /var/log/suricata/eve-alerts.json {
      daily
      missingok
      rotate 3
      nocompress
      sharedscripts
      postrotate
          suricatasc -c reopen-log-files
      endscript
    }

rule_files:
  rule1: |
    alert http any any -> any any (msg:"HTTP to duckduckgo.com"; content:"Host: duckduckgo.com"; sid:100001; rev:1;)

  rule2: |
    alert http any any -> any any (msg:"HTTP to example.com"; content:"Host: example.com"; sid:100001; rev:1;)

