# Default values for suricata.
replicaCount: 1

image:
  repository: registry.hub.docker.com/jasonish/suricata
  pullPolicy: IfNotPresent
  tag: "7.0"

interface: eth0

# Host path for suricata log volume
suricata_log_path: /opt/suricata

logrotate_config:
  suricata: |
    /var/log/suricata/*.log /var/log/suricata/*.json {
      daily
      missingok
      rotate 3
      nocompress
      sharedscripts
      postrotate
          suricatasc -c reopen-log-files
      endscript
    }
      