apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  suricata.yaml:  |

    %YAML 1.1
    ---
    stream:
      memcap: 16gb
      checksum-validation: no      # reject wrong csums
      inline: auto                  # auto will use inline mode in IPS mode, yes or no set it statically
      reassembly:
        memcap: 16gb
        depth: 1mb                  # reassemble 1mb into a stream
        toserver-chunk-size: 2560
        toclient-chunk-size: 2560
        randomize-chunk-size: yes

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logrotate
data:
  suricata: "test"
  # suricata: {{ .Values.logrotate_settings }}