apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  suricata.yaml:  |
{{ .Files.Get "files/suricata_config.yaml" | indent 4 }}
    default-rule-path: /usr/local/etc/suricata/rules
    rule-files:
{{ required "Must specify rule_files" .Values.rule_files | keys | toYaml | indent 6}}
{{- range $rule_file_name, $rules := .Values.rule_files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-rules-{{ $rule_file_name }}
data:
  {{ $rule_file_name }}: {{ quote $rules }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logrotate
data:
  suricata: {{ toYaml .Values.logrotate_config.suricata | indent 2 }}