apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels:
    component: suricata
spec:
  selector:
    matchLabels:
      component: suricata
  template:
    metadata:
      labels:
        component: suricata
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: suricata
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          capabilities: # Required to allow Suricata to function
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_NICE
        volumeMounts:
        - name: logs
          mountPath: /var/log/suricata
        args: ["-i", "{{ .Values.interface }}"]
      volumes:
      - name: logs
        emptyDir: {}
      affinity:
        podAntiAffinity: # Do not allow more than one per host
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - suricata
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity: # Specify a specific target node
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.node_label }}
                operator: In
                values:
                  - {{ .Values.node_label_value }}
